language: ruby
rvm:
  - 1.9.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cups cups-pdf cups-bsd libcups2-dev
  - sudo apt-get install -qq imagemagick libmagickwand-dev nodejs
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - 'mkdir private; mkdir private/to_print'
  - "psql -c 'create database sovs_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
