default: &default
  adapter: postgresql
  encoding: unicode
  database: sovs_development
  pool: 5
  username: docker
  password: docker
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: 5432

development:
  <<: *default
  database: sovs_development

test:
  <<: *default
  database: sovs_test

production:
  <<: *default
  # database: sovs_production
