development:
  adapter: postgresql
  encoding: unicode
  database: sovs_development
  pool: 5
  username: sovs
  password: sovs

test:
  adapter: postgresql
  encoding: unicode
  database: sovs_test
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'sovs' %>
  password: <%= ENV['TRAVIS'] ? '' : 'sovs' %>

production:
  adapter: postgresql
  encoding: unicode
  database: sovs_production
  pool: 5
  username: sovs
  password: sovs

filomena:
  adapter: sqlite3
  encoding: unicode
  database: db/filomena.sqlite3
  timeout: 5000
  pool: 5
