# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 812c042c1df04f9ced8aaa8a4935f0a5b47134fccc9894dbe06f4a02145b295f300fd12ddf24fb751a6acda9bada1814b5064d31c60c02e248091f4624b0975b

test:
  secret_key_base: a0d48b020efe887fc4109b8cb3f8a6b9eb32245da0ea57a22c76bf5be7284a572c595c2cf5f3d240f1bb7c9e7e2c80bf78aa03c5f406c180e5a14d9f76a23392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
